### PR TITLE
Adding transformer library

### PR DESCRIPTION
**Pull request by paganotoni**

### CODE REVIEW

**Comment by markbates** [comment]
Some of these are already here:

https://godoc.org/github.com/gobuffalo/genny/movinglater/gotools

Also there are some helpers, like https://godoc.org/github.com/gobuffalo/genny/movinglater/gotools#ParseFile, which should clean up a ton of code.

Try to break the transformers down like this https://godoc.org/github.com/gobuffalo/genny/movinglater/gotools#AddImport so they do only one small thing each.

**Comment by paganotoni** [comment]
Thinking if i should close this PR and redo the transformer stuff in here.

**Comment by markbates** [comment]
it's up to you.

**Comment by paganotoni** [comment]
I'll start by using what genny already have and add there what is missing.

**Pull request closed without merging**
